# Generated by Django 4.2.5 on 2023-10-11 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_brand_category_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='description',
            field=models.CharField(default='No description provided', max_length=255),
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(default='No description provided', max_length=255),
        ),
    ]
